### ISSUE TITLE
Añadir botón de eliminar publicación y añadirle funcionalidad

### ISSUE THREAD

**Issue by juliarobles** [juliarobles/graffitisWeb#10]
Este botón estará en detalles publicación y solo lo podrá ver el usuario creador. Intentaré añadir el botón cuando tenga tiempo. Recordad que la funcionalidad ya está implementada en el servidor así que solo hay que hacer el **delete** correspondiente.

**Comment by alejandroat99** [comment]
Ya he terminado el botón con su funcionalida. Sólo falta añadirle el control de seguridad para que solo el propietario de la publicación pueda borrarla.

**Comment by alejandroat99** [comment]
He puesto la seguridad del inicio de sesión para que sólo se muestre el botón de borrado en las publicaciones del usuario y tambíen en la parte de views para evitar que se llame directamente al enlace.
