### ISSUE TITLE
Subir a la nube

### ISSUE THREAD

**Issue by juliarobles** [juliarobles/graffitisWeb#16]

**Comment by juliarobles** [comment]
Lo pongo difícil porque podría llevar mucho tiempo si da muchos fallos. Además hay que recalcar que es importante.

**Comment by juliarobles** [comment]
**Importante:** cuando se suba a la nube hay que añadir en CORS_ORIGIN_WHITELIST de settings.py la url del dominio.

**Comment by alejandroat99** [comment]
Acabo de subir una actualización con los archivos y requisistos necesarios para desplegar la aplicación en Heroku. Solo faltaría realizar la configuración necesaria en el archivo setting.py

**Comment by juliarobles** [comment]
**Importante:** si OAuth no funciona al subirlo a la nube probablemente sea porque no se guarda la sesión. Mirad los mensajes que pasé por el grupo.

**Comment by alejandroat99** [comment]
La aplicación ya se encuentra disponible en Heroku en la dirección https://graffitisweb-c4.herokuapp.com. Se necesitarán pruebas para encontrar los posibles errores.
