### ISSUE TITLE
Restringir número de caracteres en los formularios y aclarar que la temática debe ser introducida con #

### ISSUE THREAD

**Issue by juliarobles** [juliarobles/graffitisWeb#18]

**Comment by DanielRuiz14** [comment]
He hecho la validación en el lado del cliente. Faltaría la validación del lado del servidor pero esto implicaría mucho trabajo para una funcionalidad de nivel medio-bajo. Por tanto, he decidido seguir con otras funcionalidades de prioridad más alta y seguir con esto más adelante.
