### ISSUE TITLE
Modificar campo de coordenadas en los modelos

### ISSUE THREAD

**Issue by pepedg** [juliarobles/graffitisWeb#20]
- Añadir campo al modelo de publicación.
- Añadir campos para coordenadas en el formulario para añadir un nuevo graffiti.

**Comment by juliarobles** [comment]
Creo que el atributo ubicación o algo así que tenemos es justo para eso, solo que por ahora habíamos puesto Malaga. Lo que si es que habrá que comprobar en el input que es una coordenada o darlo a elegir desde un mapa.

**Comment by juliarobles** [comment]
Campo modificado. Ahora permite únicamente añadir coordenadas (comprobado con pattern) y se puede seleccionar directamente de un mapa o ponerlas manualmente.
