### ISSUE TITLE
Añadir funcionalidad de ver mapa

### ISSUE THREAD

**Issue by pepedg** [juliarobles/graffitisWeb#21]
- Sopesar que alternativa nos conviene más usar.
- Añadir el mapa en la vista de publicación.

**Comment by juliarobles** [comment]
Inicio:
-Mostrar la información de las publicaciones al pulsar sobre un marcador.
-Poner ubicación actual del usuario.

Detalles publicación:
-Mostrar en un mapa la ubicación del graffiti.

Añadir publicación:
-Elegir ubicación respecto a un mapa (dejar también añadir coordenadas?)

**Comment by juliarobles** [comment]
Todo lo anterior hecho. Issue terminado.
