### ISSUE TITLE
Integración API externa 2

### ISSUE THREAD

**Issue by juliarobles** [juliarobles/graffitisWeb#27]
Integrará otros servicios web externos, además de los indicados, como por ejemplo, información meteorológica, niveles de contaminación, etc

**Comment by DanielRuiz14** [comment]
Este Issue se refiere a las APIs  que no son la del ayuntamiento de Málaga, no?

**Comment by juliarobles** [comment]
Efectivamente

**Comment by DanielRuiz14** [comment]
Me la asigno pero si alguien quiere hacerla conmigo no voy a oponerme. 😳😳

**Comment by DanielRuiz14** [comment]
Hemos pensado en usar esta [API](https://palett.es/api) que genera paletas de colores. El usuario obtendrá una paleta aleatoria según el número de colores que quiera. Con esta paleta "deberá" de crear un graffiti y subirlo. (Si no le baneamos la cuenta).

**Comment by DanielRuiz14** [comment]
He integrado la API con Ajax para que no haya que refrescar la página para generar la paleta. Sin embargo, no sé muy bien cómo introducirlo en la página. Se lo dejo a mi compañero que aún no ha aparecido.
