### ISSUE TITLE
Cambiar raiz de la aplicación

### ISSUE THREAD

**Issue by juliarobles** [juliarobles/graffitisWeb#30]
Mover la api a /api y poner como raíz de la aplicación lo que ahora mismo es /principal

**Comment by alejandroat99** [comment]
He cambiado las direcciones y he configurado el archivo ulr principal para que cada aplicación que se va a usar tenga un namespace para poder usar la función reverse sobre urls de otras de las aplicaciones.
No lo subo todavía ya que parecen haber errores.

**Comment by DanielRuiz14** [comment]
He cambiado la mayoría de las urls de acceso a nuestra API. Además, he añadido una variable en caso de que tengamos que cambiar la url base de la API.
