### ISSUE TITLE
Crear formulario de crear graffiti y añadirle funcionalidad.

### ISSUE THREAD

**Issue by juliarobles** [juliarobles/graffitisWeb#6]
Este formulario debe ser IGUAL al formulario de añadir publicación pero solo con la parte que corresponde al graffiti. Así mantendremos la consistencia en la página. Por tanto quien lo vaya a hacer que se espere a que el formulario de crear publicación esté terminado. Recordad que la funcionalidad ya está implementada en el servidor así que solo hay que hacer el post correspondiente. Del mismo modo aquí también se debe usar **Imgur** para subir las imágenes. El botón para acceder a este formulario se llamará "Añadir contribución" y se encontrará en detalles publicación. Por ahora no está añadido pero intentaré añadirlo cuando tenga tiempo, si no es el caso añadid un botón normal y luego modifico el diseño si fuese necesario.

**Comment by alejandroat99** [comment]
Ya hay funcionalidad para insertar una nueva contribución a una publicación, sólo falta subir la imagen a Flickr.

**Comment by alejandroat99** [comment]
Código actualizado para subir la foto a Flicker y obtener la url para que se vea la imagen en los detalles de la publicación.
