### ISSUE TITLE
Añadir botón de eliminar contribución y añadirle funcionalidad

### ISSUE THREAD

**Issue by juliarobles** [juliarobles/graffitisWeb#7]
Si el graffiti pertenece al usuario de la sesión, este podrá eliminar la contribución. Recordad que la funcionalidad ya está implementada en el servidor así que solo hay que hacer el delete correspondiente. IMPORTANTE -> En el caso de ser el creador de la publicación, NO podrá borrar el graffiti con el que lo publicó (primer graffiti de la publicación nunca tendrá ese botón). Si quisiera borrarlo tendría que eliminar la publicación entera.

**Comment by alejandroat99** [comment]
He subido una versión que coloca un botón de borrado en los graffitis dependiendo del usuario que ha iniciado sesión. Tambíen se comprueba que el usuario ha iniciado sesión en el lado del servidor.
