### ISSUE TITLE
Añadir botón de editar contribución y añadir funcionalidad

### ISSUE THREAD

**Issue by juliarobles** [juliarobles/graffitisWeb#8]
Se permitirá al usuario de la sesión editar SUS graffitis. Este botón será añadido a detalles publicación. Intentaré añadirlo yo cuando me sobre algo de tiempo. Para hace falta que se haga primero el crear graffiti para tener el formulario y por supuesto el inicio de sesión. Recordad que la funcionalidad ya está implementada en el servidor así que solo hay que hacer el **put** correspondiente.

**Comment by juliarobles** [comment]
Botón añadido, falta funcionalidad

**Comment by juliarobles** [comment]
Lo dejamos por ahora como posibilidad para 3 entrega

**Comment by DanielRuiz14** [comment]
Funcionalidad implementada. Cierro issue.
