### ISSUE TITLE
Añadir botón de editar publicación y añadir funcionalidad

### ISSUE THREAD

**Issue by juliarobles** [juliarobles/graffitisWeb#9]
Este botón será añadido a detalles publicación y solo se podrá ver si el usuario de sesión es el creador, intentaré añadirlo cuando tenga tiempo y cuando el inicio de sesión esté hecho. Para hacer esto es necesario que antes esté hecho el formulario de crear publicación, ya que compartirán template. Recordad que la funcionalidad ya está implementada en el servidor así que solo hay que hacer el **put** correspondiente.

**Comment by juliarobles** [comment]
Botón añadido, falta funcionalidad

**Comment by albertcast** [comment]
Modificar el funcionamiento: edicion del primer graffiti

**Comment by juliarobles** [comment]
Listo
